USE BOOK;

CREATE TABLE DOCUMENT(
	ID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	AUTHOR VARCHAR(50),
	YEAR INT,
	QUANTITY INT
)

CREATE TABLE BOOK(
	ID INT NOT NULL IDENTITY(1, 1),
	BOOKID VARCHAR(50) NOT NULL PRIMARY KEY,
	TYPE VARCHAR(50),
	DOCID INT,
	FOREIGN KEY (DOCID) REFERENCES DOCUMENT(ID)
)

